'use strict';
const musicData = [
  {
    backgroundImage: "https://masumbillah6778.github.io/images/lalon.png",
    posterUrl: "https://masumbillah6778.github.io/images/lalon.png",
    title: "1. Piya Re",
    album: "No Spirit",
    year: 2025,
    artist: "No Spirit x Tonion",
    musicPath: "https://github.com/masumbillah6778/best-of-zubeen-garg/raw/main/piya-re-piya-re.mp3",
  },
  {
    backgroundImage: "https://masumbillah6778.github.io/images/lalon.png",
    posterUrl: "https://masumbillah6778.github.io/images/lalon.png",
    title: "2. We Are Going To Be Ok (Master)",
    album: "No Spirit",
    year: 2022,
    artist: "No Spirit x Jhove",
    musicPath: "https://github.com/masumbillah6778/best-of-zubeen-garg/raw/main/piya-re-piya-re.mp3",
  },
  {
    backgroundImage: "https://masumbillah6778.github.io/images/lalon.png",
    posterUrl: "https://masumbillah6778.github.io/images/lalon.png",
    title: "Winter Meadow",
    album: "No Spirit",
    year: 2022,
    artist: "No Spirit x  juniorodeo",
    musicPath: "./assets/music/music-3.mp3",
  },
  {
    backgroundImage: "https://masumbillah6778.github.io/images/lalon.png",
    posterUrl: "https://masumbillah6778.github.io/images/lalon.png",
    title: "From Where We Started",
    album: "No Spirit",
    year: 2022,
    artist: "No Spirit",
    musicPath: "./assets/music/music-4.mp3",
  },
  {
    backgroundImage: "https://masumbillah6778.github.io/images/lalon.png",
    posterUrl: "https://masumbillah6778.github.io/images/lalon.png",
    title: "Where I Found You",
    album: "No Spirit",
    year: 2022,
    artist: "No Spirit",
    musicPath: "./assets/music/music-5.mp3",
  },
];
